<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Gogoprint\AddToCart\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>

<h3 class="option-title"><?php /* @escapeNotVerified */ echo __('Step 2: Choose the Quantities and Delivery Date:') ?></h3>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty" >
            <div class="control" style="visibility: hidden;">
                       <?php 
                        $getOptionValue = $this->getQtyIncrements();
                        $optionQty = array_shift($getOptionValue);
                       ?>
                    
                        <?php foreach($getOptionValue as $quantity){ ?>
                          <label class="radio">
                            <input type="radio" 
                                    name="qty" 
                                    data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                    value="<?php echo $quantity;?>"
                                    title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                            >
                            <?php echo $quantity;?>
                          </label>
                         
                        <?php } ?>
                        
            </div>

            
    <table id="configure-optionPrice">
        <tr>
            
            <th class="info">
                <span class="qty-title">
                    <?php /* @escapeNotVerified */ echo __('Qty') ?>
                </span>
                <span class="date-title">
                    <?php /* @escapeNotVerified */ echo __('Delivery') ?>
                </span>

            </th>
            <?php echo $this->getRowDate();?>
        </tr>
       
            <?php echo $this->getColQty();?>
       
    </table>
     
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Gogoprint_AddToCart/js/catalog-product-add-to-cart": {
                    "catalogProductAddToCart": {
                        "bindSubmit": false
                    }
                }
            }
        }
    </script>
<?php endif; ?>
